### ISSUE TITLE
Feature Parity with React 16 Checklist

### ISSUE THREAD

**Issue by kealjones-wk** [KealJones/reactor#3]
- [x] React.Component and lifecycle methods (including error boundary lifecycles)
- [x] React.Fragment component
- [ ] React.StrictMode component
- [ ] React.Profiler component (and "interaction-tracking" package)
- [ ] React.Suspense component
- [ ] React.memo
- [ ] React.forwardRef
- [ ] React.lazy
- [ ] Class.contextType
- [ ] ReactDOM.createPortal
- [ ] New Context API
- [ ] SyntheticEvents (including New Pointer Events)
- [ ] React Hooks 
- [ ] Investigate Custom Hooks
