### ISSUE TITLE
Feature Parity with React 16 Checklist

### ISSUE THREAD

**Issue by KealJones** [KealJones/reactor#4]
## [Function and Class Components](https://reactjs.org/docs/components-and-props.html#function-and-class-components)
- [x] React.Component and lifecycle methods (including error boundary lifecycles)
- [x] Functional Components
  - This has been partially implemented but we are still exploring other syntaxes.

## [Top Level API](https://reactjs.org/docs/react-api.html#reference)
- [x] React.createElement()
- [ ] React.memo

## [Fragments](https://reactjs.org/docs/fragments.html)
- [x] React.Fragment component

## [Strict Mode](https://reactjs.org/docs/strict-mode.html)
- [x] React.StrictMode component

## [SyntheticEvents](https://reactjs.org/docs/events.html)
- [ ] DOM Events
- [ ] New Pointer Events

## [Context](https://reactjs.org/docs/context.html)
- [ ] React.createContext
- [ ] Context.Provider component
- [ ] Context.Consumer component
- [ ] Class.contextType

## [Profiler](https://reactjs.org/docs/profiler.html)
- [ ] React.Profiler component (and "interaction-tracking" package)

## [Portals](https://reactjs.org/docs/portals.html)
- [ ] ReactDOM.createPortal

## [Refs](https://reactjs.org/docs/react-api.html#refs)
- [ ] React.createRef
- [ ] React.forwardRef

## [Suspense](https://reactjs.org/docs/react-api.html#suspense)
- [ ] React.lazy
- [x] React.Suspense component

## [Hooks](https://reactjs.org/docs/react-api.html#hooks)
- [x] Basic Hooks
  - [x] `useState`
  - [x] `useEffect`
  - [x] `useContext`
- [x] Additional Hooks
  - [x] `useReducer`
  - [x] `useCallback`
  - [x] `useMemo`
  - [x] `useRef`
  - [x] `useImperativeHandle`
  - [x] `useLayoutEffect`
  - [x] `useDebugValue`
- [ ] Custom Hooks?
